# Generated by Django 3.2.12 on 2022-04-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование аллергии')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=2048, verbose_name='Описание')),
                ('recipe', models.CharField(blank=True, max_length=2048, verbose_name='Рецепт приготовления')),
                ('calories', models.CharField(default='', max_length=20, verbose_name='Калорийность')),
                ('picture', models.URLField(max_length=1024, verbose_name='Ссылка на картинку')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование меню')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '_Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (+код xxx xxx-xx-xx)'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_paid',
            field=models.BooleanField(default=False, verbose_name='Подписка оплачена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_meals', models.IntegerField(default=1, verbose_name='Количество приёмов пищи за день')),
                ('number_of_person', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('duration', models.IntegerField(default=1, verbose_name='Длительность подписки, мес.')),
                ('allergy', models.ManyToManyField(to='tgbot.Allergy', verbose_name='Аллергии')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_menu_type', to='tgbot.menutype', verbose_name='Тип меню')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписка',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Ингредиент')),
                ('amount', models.CharField(default='', max_length=20, verbose_name='Количество')),
                ('unit', models.CharField(default='', max_length=255, verbose_name='Единица измерения')),
                ('allergy', models.ManyToManyField(related_name='ingredient_allergy', to='tgbot.Allergy')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_dish', to='tgbot.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюд',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_menu_type', to='tgbot.menutype', verbose_name='Тип меню'),
        ),
    ]
