# Generated by Django 3.2.12 on 2022-04-02 09:36

from django.db import migrations
from tgbot.models import Allergy, MenuType


def full_default_data(apps, schema_editor):
    Allergy(sort_order=0, name='нет').save()
    Allergy(sort_order=1, name='Рыба и морепродукты').save()
    Allergy(sort_order=1, name='Мясо').save()
    Allergy(sort_order=1, name='Зерновые').save()
    Allergy(sort_order=1, name='Продукты пчеловодства').save()
    Allergy(sort_order=1, name='Орехи и бобовые').save()
    Allergy(sort_order=1, name='Молочные продукты').save()

    MenuType(name='Классическое').save()
    MenuType(name='Низкоуглеводное').save()
    MenuType(name='Вегетарианское').save()
    MenuType(name='Кето').save()


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20220402_0924'),
    ]

    operations = [
        migrations.RunPython(full_default_data),
    ]
