# Generated by Django 3.2.12 on 2022-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергия',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('recipe', models.CharField(blank=True, max_length=2048)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Тип меню',
            },
        ),
    ]
