# Generated by Django 3.2.12 on 2022-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_auto_20220402_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование'),
        ),
    ]
