# Generated by Django 3.2.12 on 2022-03-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_allergy_dish_menutype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование аллергии'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Рецепт приготовления'),
        ),
        migrations.AlterField(
            model_name='menutype',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование меню'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_meals', models.IntegerField(default=1, verbose_name='Количество приёмов пищи за день')),
                ('number_of_person', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_allergy', to='tgbot.allergy', verbose_name='Аллергия')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_menu_type', to='tgbot.menutype', verbose_name='Тип меню')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписка',
            },
        ),
    ]
