# Generated by Django 3.2.12 on 2022-04-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_allergy_options'),
        ('tgbot', '0004_alter_dish_name'),
    ]

    operations = [
    ]
