# Generated by Django 3.2.12 on 2022-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20220330_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='subscription_duration',
            field=models.IntegerField(default=1, verbose_name='Длительность подписки, мес.'),
        ),
    ]
