# Generated by Django 3.2.12 on 2022-03-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_subscribe_subscription_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subscription_duration',
            new_name='duration',
        ),
    ]
