# Generated by Django 3.2.12 on 2022-03-31 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_rename_subscription_duration_subscribe_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '_Пользователи'},
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.FloatField(default=0.0, verbose_name='Калорийность'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_menu_type', to='tgbot.menutype', verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Ингредиент')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('unit', models.CharField(default='', max_length=255, verbose_name='Единица измерения')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_dish', to='tgbot.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюд',
            },
        ),
    ]
