# Generated by Django 3.2.12 on 2022-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_dishingredient_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='amount',
            field=models.CharField(default='', max_length=20, verbose_name='Количество'),
        ),
    ]
